     /* ***************** */
    /*     HOMEWORK-2    */
   /*  	Ugurcan Polat   */
  /*	  150140117    */
 /*	polatu@itu.edu.tr */
/* ***************** */

#include <stdio.h> //printf(), scanf()
#include <math.h> // pow()

void mid_rng(long *number);
void lsd_rng(long *number);
void take_samples(long number, int *r1, int *r2, int *r3, int *r4, int *r5);
void print_histogram(int num_samples, int r1, int r2, int r3, int r4, int r5);

int main (){
	/* Define and initialize necessary numbers. */
	int prng, num_samples = 0, counter;
	int r1 = 0, r2 = 0, r3 = 0, r4 = 0, r5 = 0; //Ranges
	long number;
	
	/* Get necessary inputs from user to generate random numbers. */
	printf("$ Which PRNG Algorithm?\n");
	printf("  1. MID-PRNG\n  2. LSD-PRNG\n$ ");
	scanf("%d", &prng);
	
	/* Check entered number and gives error if it is not valid choice for algorithm. */
	while (prng != 1 && prng != 2) {
		printf("\n * Please enter valid parameter to select algorithm *\n");
		printf("  1. MID-PRNG\n  2. LSD-PRNG\n$ ");
		scanf("%d", &prng);		
	} //while
	
	printf("$ Enter the seed\n$ ");
	scanf("%ld", &number);

	/* Checks entered number and gives error if it has not 5 digits. */
	while ((number / pow(10,4) < 1) || (number / pow(10,5) > 1) || number <= 0) {
		printf("\n* Seed must be positive and have 5 digits *\n\n");
		printf("$ Enter the seed\n$ ");
		scanf("%ld", &number);
	} //while
	
	/* Checks entered number and gives error if it can be */
	/* divided by 2 or 5 when using LSD-PRNG algorithm. */
	while (((number % 2 == 0) || (number % 5 == 0 )) && prng == 2){
		printf("\n* Seed must be neither even nor ends in a 5 to use LSD-PRNG *\n\n");
		printf("$ Enter the seed\n$ ");
		scanf("%ld", &number);
	} //while
	
	printf("$ Enter Number of Samples\n$ ");
	scanf("%d", &num_samples);
	
	/* Checks entered number and gives error if it is not positive */
	while (num_samples <= 0){
		printf("\n* Number of Samples must be positive. *\n");
		printf("$ Enter Number of Samples\n$ ");
		scanf("%d", &num_samples);
	} //while
	
	/* End get numbers from user. */
	
	printf("$ %d random numbers were ", num_samples);
	
	/* Use MID-PRNG if user entered '1' for prng value */
	if (prng == 1){
		printf("generated by using MID-PRNG:\n");	
		/* Generate random numbers until number of samples */
		/* reaches to num_samples entered by user. */
		for (counter = 1; counter <= num_samples; counter++){
			/* Call mid_rng function to generate a random number. */
			mid_rng(&number);
			/* Call take_samples to map generated number into ranges (1-5). */
			take_samples(number, &r1, &r2, &r3, &r4, &r5);
		} //for
	} //if(prng) 
	
	else if (prng == 2){
		printf("generated by using LSD-PRNG:\n");
		/* Generate random numbers until number of samples */
		/* reaches to num_samples entered by user. */
		for (counter = 1; counter <= num_samples; counter++){
			/* Call lsd_rng function to generate a random number. */
			lsd_rng(&number);
			/* Call take_samples to map generated number into ranges (1-5). */
			take_samples(number, &r1, &r2, &r3, &r4, &r5);
		} //for
	} //else if(prng)
	
	/* Call histogram function to print histogram of samples. */
	print_histogram(num_samples, r1, r2, r3, r4, r5);
	return 0;
} //main

/* 'Middle Digits' RNG algorithm */
void mid_rng(long *number) { 
	long square, first_digits;
	float check;
	int x, a = 0, b = 0;
	square = *number * *number;
	
	/* Find the number of digits 'square' has and store it into 'x' */
	for (x = 1; ; x++){
		check = square / pow(10,x);
		if (check <= 1)
			break;
	} //for
	
	/* If number of digits more than 5, then get middle 5 digits */
	if (x > 5){
		/* Find the number of digits the program deal with them */
		/* while getting rid of first digits of squared number */
		/* 'a' will be used to get rid of first digits */
		/* 'b' will be used to get rid of last digits */ 
		/* At last, these calculations will give a 5-digit random number */
		b = (x - 5) / 2;
		a = x - b;
			
		/* If number of digits is even increment 'b' by 1. */
		if (!(x % 2))
			b += 1;
			
		/* Get first 'a' digits of square that we want to get rid of */	
		first_digits = square / pow(10,a);
		/* Get rid of first 'a' digits. */
		square = square - (first_digits * pow(10,a));
		/* Get rid of last digits to get 5 digit random number. */
		*number = square / pow(10,b);
	} //if(x > 5)
	
	/* If number of digits less than or equal to 5, then use squared number */
	else 
		*number = square;	
} //mid_rng()

/* 'Least Significant Digits' RNG algorithm */
void lsd_rng(long *number) {
	long product = 0, first_digits;

	product = *number * 73;	
	/* Get first digits of the product that come after last 5 digits */		
	first_digits = product / pow(10,5);
	/* Get rid of first digits to get 5 digit random number. */
	*number = product - (first_digits * pow(10,5));	
} //lsd_rng()

/* Function for mapping generated samples. */
/* Increments selected range after mapping. */
void take_samples(long number, int *r1, int *r2, int *r3, int *r4, int *r5) {
	int mapper = (number % 500) + 1;
	
	if (mapper <= 100)
		*r1 += 1;
	else if (mapper >= 101 && mapper <= 200)
		*r2 += 1;
	else if (mapper >= 201 && mapper <= 300)
		*r3 += 1;
	else if (mapper >= 301 && mapper <= 400)
		*r4 += 1;
	else if (mapper >= 401 && mapper <= 500)
		*r5 += 1;		
} //take_samples()

void print_histogram(int num_samples, int r1, int r2, int r3, int r4, int r5) {
	int counter;
	/* Calculate percentages of ranges.*/
	int percentage1 = (r1 * 100) / num_samples;
	int percentage2 = (r2 * 100) / num_samples;
	int percentage3 = (r3 * 100) / num_samples;
	int percentage4 = (r4 * 100) / num_samples;
	int percentage5 = (r5 * 100) / num_samples;

	/* Prints Range1 (1..100). */
	printf("  1..100: ");
	for (counter = 1; counter <= percentage1; counter++) {
		printf("*");
	} //for
	printf(" (%d%%)", percentage1);
	
	/* Prints Range2 (101..200). */
	printf("\n101..200: ");
	for (counter = 1; counter <= percentage2; counter++) {
		printf("*");
	} //for
	printf(" (%d%%)", percentage2);
	
	/* Prints Range3 (201..300). */
	printf("\n201..300: ");
	for (counter = 1; counter <= percentage3; counter++) {
		printf("*");
	} //for
	printf(" (%d%%)", percentage3);
	
	/* Prints Range4 (301..400). */
	printf("\n301..400: ");
	for (counter = 1; counter <= percentage4; counter++) {
		printf("*");
	} //for
	printf(" (%d%%)", percentage4);
	
	/* Prints Range5 (401..500). */
	printf("\n401..500: ");
	for (counter = 1; counter <= percentage5; counter++) {
		printf("*");
	} //for
	printf(" (%d%%)\n\n", percentage5);	
} //print_histogram()
